# Reminder: The argument --build must be used with docker-compose when making any updates to
# traefik.toml as the file needs to be re-copied due to the use of a Dockerfile.
version: "3.6"

services:
  traefik:
    hostname: traefik
    build:
      context: ./traefik
      dockerfile: docker/aws/Dockerfile
    container_name: traefik
    restart: always
    domainname: "metric-teacher.com"
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.enable=true"
      # Load the monitor by visiting ...metric-teacher.com/traefik - it may require a new browser window to work.
      - "traefik.frontend.rule=HostRegexp:{subdomain:.+}.metric-teacher.com,metric-teacher.com;PathPrefixStrip:/traefik"
      - "traefik.port=8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  metric-teacher-client:
    container_name: metric-teacher-client
    restart: always
    build:
      context: .
      dockerfile: docker/${METRIC_TEACHER_CLIENT_BUILD_MODE:-prebuilt}/Dockerfile
    command: "serve --single --listen=3000 ./build"
    networks:
      - proxy
    labels:
      - "traefik.backend=metric-teacher-client"
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.frontend.rule=HostRegexp:{subdomain:.+}.metric-teacher.com,metric-teacher.com"
      - "traefik.port=3000"

networks:
  proxy:
    name: "proxy"
    external: false
