version: "3.6"

services:
  traefik:
    hostname: traefik
#    image: traefik:latest  # Until volume mounting is fixed...
    build:                  # Until volume mounting is fixed...
      context: .
      dockerfile: traefikDockerfile
    container_name: traefik
    restart: always
    domainname: "metric-teacher.com"
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=HostRegexp:{subdomain:.+}.metric-teacher.com,metric-teacher.com;PathStrip:/traefik"
      - "traefik.port=8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#      - ./traefik.toml:/traefik.toml # Until volume mounting is fixed...
      - ./acme.json:/acme.json

  metric-teacher-client:
    container_name: metric-teacher-client
    restart: always
    build:
      context: .
      dockerfile: docker/${METRIC_TEACHER_CLIENT_BUILD_MODE:-prebuilt}/Dockerfile
    command: "serve --single --listen=3000 ./build"
    networks:
      - proxy
    labels:
      - "traefik.backend=metric-teacher-client"
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.frontend.rule=HostRegexp:{subdomain:.+}.metric-teacher.com,metric-teacher.com"
      - "traefik.port=3000"

networks:
  proxy:
    name: "proxy"
