version: "3.6"

services:
  metric-teacher-server:
    container_name: metric-teacher-server
    restart: always
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    command: "yarn start-prod"
    ports:
      - "80:4000" # For prod use on api.metric-teacher.com

volumes:
  metric-teacher-server:
