const constants = {
  // Generic
  FLAGS_NONE: 0,

  // User
  USER_TYPE_STUDENT: 0,
  USER_TYPE_TEACHER: 1,
  USER_TYPE_MODERATOR: 2,
  USER_TYPE_ADMIN: 3,

  USER_STATUS_NORMAL: 0,
  USER_STATUS_CLOSED: 1,

  // Classroom
  CLASSROOM_STATUS_ACTIVE: 0,
  CLASSROOM_STATUS_INACTIVE: 1,

  // Course
  COURSE_STATUS_ACTIVE: 0,
  COURSE_STATUS_INACTIVE: 1,

  // Mastery
  MASTERY_DEFAULT_SCORE: 0,
  MASTERY_STATUS_ACTIVE: 0,
  MASTERY_STATUS_INACTIVE: 1,

  // Question
  QUESTION_TYPE_WRITTEN: 0,
  QUESTION_TYPE_CONVERSION: 1,
  QUESTION_TYPE_SURVEY: 2,
  QUESTION_STATUS_ACTIVE: 0,
  QUESTION_STATUS_INACTIVE: 1,
  QUESTION_DIFFICULTY_EASY: 1,
  QUESTION_DIFFICULTY_EASY_MEDIUM: 2,
  QUESTION_DIFFICULTY_MEDIUM: 3,
  QUESTION_DIFFICULTY_MEDIUM_HARD: 4,
  QUESTION_DIFFICULTY_HARD: 5,

};

module.exports = constants;
