const constants = {
  // Generic
  FLAGS_NONE: 0,

  // User
  USER_TYPE_STUDENT: 0,
  USER_TYPE_TEACHER: 1,
  USER_TYPE_MODERATOR: 2,
  USER_TYPE_ADMIN: 3,

  USER_STATUS_NORMAL: 0,
  USER_STATUS_CLOSED: 1,

  // Classroom
  CLASSROOM_STATUS_ACTIVE: 0,
  CLASSROOM_STATUS_INACTIVE: 1,

  // Course
  COURSE_STATUS_ACTIVE: 0,
  COURSE_STATUS_INACTIVE: 1,

  // Mastery
  MASTERY_DEFAULT_SCORE: 0,
  MASTERY_STATUS_ACTIVE: 0,
  MASTERY_STATUS_INACTIVE: 1,
};

module.exports = constants;
